version: '2'
services:
  tileserver:
    image: klokantech/tileserver-gl:v1.1.5
    ports:
      - "8080:80"
    volumes:
      - ./tileserver-gl/:/data/:ro
  webserver:
    image: kpn/php-base:0.1
    ports:
      - "80:80"
    volumes:
      - ./web-server/:/var/www/html/
